### ISSUE TITLE
Single Payment, Multiple Invoices

### ISSUE THREAD

**Issue by dancameron** [dancameron/sprout-invoices-auto-billing#10]
> Would it be possible for a client to be able to pay their full balance due (including more than one invoice) in one payment, rather than multiple payments?

Not at this time...I'm not even sure how that would be possible since each payment would be tied to each invoice.

**Comment by ddeitz** [comment]
(ex) Someone wants to pay their full balance due in one payment

I think my example is more relevant in a payment being applied to the entire balance due, whether it be 1,2, or 3 invoices combined to make up that entire balance due.

**Comment by dancameron** [comment]
The only way I see this working:

The client already has a payment profile setup, then select the invoices they want to pay on their dashboard and click submit. Or they have a payment profile and there's a button they client to charge all outstanding invoices.

I don't see the viability with this "nice to have" feature though, since it would be a lot of work for something that doesn't save the client all that much time, since they could go to each and select their saved payment profile...or the admin can do it via the ajax button.

**Comment by ddeitz** [comment]
I agree. Our company has been altering our billing procedures, so forgive me if any of my requests sound strange. I'm trying to simplify things and you're helping a great deal. :)

If both options you've listed above are a significant amount of work, then we can move forward and ignore this feature.

**Comment by dancameron** [comment]
Let's finish things up first and loop back later after everything is settled. That way you'll really know if you need this or not.
