### ISSUE TITLE
Custom CSV Import

### ISSUE THREAD

**Issue by dancameron** [dancameron/sprout-invoices-auto-billing#11]
> See attached for a sample csv file for the invoice import.

I'm a bit perplexed by this, not only with it's formatting but why I'm receiving it now. I was under the impression that you were formatting your CSV import to match what SI already needs. 

Are you needing me to create a custom CSV importer that accommodates this formatting?

**Comment by ddeitz** [comment]
Dan, we can manipulate the data, but additional fields such as, account
number, will need to be added. I will follow-up more shortly.

Thank you,

*Destiny Deitz*
*Sales & Marketing Coordinator*
*Westpark Communications, L.P*.
20475 State Highway 249, Suite 100
Houston, TX 77070
Ph: 713.785.3238
Fx: 713.977.5944

<http://www.westparkcom.net/> <https://www.facebook.com/Westparkcom>
<http://www.linkedin.com/company/854512>
<https://plus.google.com/115805397773385459794>
<https://twitter.com/westparkcom>
Confidentiality Notice: The information contained in or attached to this
message may be privileged and confidential and protected from disclosure.
If the reader of this message is not the intended recipient, or an employee
or agent responsible for delivering this  message to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify us immediately and delete the
message as received.

**Comment by dancameron** [comment]
@ddeitz Before following up make sure you refer to my comment over at #9...

> Client Identifier: The identifier is the "Company" column within the CSV import. In your example CSV that you provided (#11) you would probably want to make the Company column a mix of "Customer_Name" and "Customer_Account", e.g. "ADOBE EQUIPMENT (170)", otherwise you will run into conflicts.

**Comment by ddeitz** [comment]
Absolutely. In progress of preparing my responses.

Destiny Deitz
Sales & Marketing Coordinator
Westpark Communications, L.P.
20475 State Hwy. 249, Suite 100
Houston, TX 77070
Ph:  713.785.3238
Fax: 713.977.5944

Confidentiality Notice: The information contained in or attached to this message may be privileged and confidential and protected from disclosure. if the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this  message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately and delete the message as received.

**Comment by ddeitz** [comment]
The combination of the account name and account number seems like an easy solution.

**Comment by dancameron** [comment]
I'm going to close this than since it seems like you're going to be working with the default importer.

**Comment by ddeitz** [comment]
Sounds good.
