### ISSUE TITLE
New Payment Options Not Showing on Invoice

### ISSUE THREAD

**Issue by dancameron** [dancameron/sprout-invoices-auto-billing#6]
Example: http://westpark.actwd.net/westpark-communications-invoice/f11406bac23ae458fb9e90a2df5c456c/

**Comment by dancameron** [comment]
@westparkcom Please provide admin access to the site so I can review your payment settings. It seems as though Authorize.net CIM isn't loaded.

**Comment by ddeitz** [comment]
Dan, you can use these credentials:

username: dld (all lowercase)
password: Westpark!3238

Thank you,

*Destiny Deitz*
*Sales & Marketing Coordinator*
*Westpark Communications, L.P*.
20475 State Highway 249, Suite 100
Houston, TX 77070
Ph: 713.785.3238
Fx: 713.977.5944

<http://www.westparkcom.net/> <https://www.facebook.com/Westparkcom>
<http://www.linkedin.com/company/854512>
<https://plus.google.com/115805397773385459794>
<https://twitter.com/westparkcom>
Confidentiality Notice: The information contained in or attached to this
message may be privileged and confidential and protected from disclosure.
If the reader of this message is not the intended recipient, or an employee
or agent responsible for delivering this  message to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify us immediately and delete the
message as received.

**Comment by ddeitz** [comment]
The bank account fields are still missing when attempting to pay an invoice.
http://westpark.actwd.net/westpark-communications-invoice/f11406bac23ae458fb9e90a2df5c456c/

![image](https://cloud.githubusercontent.com/assets/11576128/8840857/75aa7d44-30ac-11e5-83e1-659ddc1ff97d.png)

Also, the [sprout_invoices_payments_dashboard] shortcut isn't working now.
http://westpark.actwd.net/billpay/
![image](https://cloud.githubusercontent.com/assets/11576128/8840885/d4160916-30ac-11e5-9848-859986f82627.png)

I've tested the auth.net payment app and was able to successfully process a payment. Let me know if you need any information from me regarding our Auth.net CIM.

**Comment by dancameron** [comment]
CIM wasn't activated under payment settings - http://s-v.me/c2SR
It is now and I've also updated the plugin to the latest release.

I also activated your site license since it wasn't allowing for auto-updates...I upgraded SI to 7.6 just now.

**Comment by ddeitz** [comment]
Great. Thank you, Dan.

Thank you,

*Destiny Deitz*
*Sales & Marketing Coordinator*
*Westpark Communications, L.P*.
20475 State Highway 249, Suite 100
Houston, TX 77070
Ph: 713.785.3238
Fx: 713.977.5944

<http://www.westparkcom.net/> <https://www.facebook.com/Westparkcom>
<http://www.linkedin.com/company/854512>
<https://plus.google.com/115805397773385459794>
<https://twitter.com/westparkcom>
Confidentiality Notice: The information contained in or attached to this
message may be privileged and confidential and protected from disclosure.
If the reader of this message is not the intended recipient, or an employee
or agent responsible for delivering this  message to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify us immediately and delete the
message as received.
