### ISSUE TITLE
CSV Invoice Importing Workflow

### ISSUE THREAD

**Issue by dancameron** [dancameron/sprout-invoices-auto-billing#9]
This will be the issue that handles all the CSV importing requirements.

Based on [this workflow](http://s-v.me/bWjL) the basics requirements are:

1. Import Invoices
2. Send Invoices to clients without payment profile
3. Review the invoices and attempt to manually charge
 1. If automatic payment is not available after importing

**Comment by dancameron** [comment]
>> For importing: I need to know what you need to have added, see my notes here -https://github.com/dancameron/sprout-invoices-auto-billing/issues/4
I believe you don’t need the current CSV importing changed because of the new cron setup to automatically charge on the due date. 
> Why would this cause us not to need the change? 

See above for the requirements of your workflow...this is how it would work:

1. Import CSV file and new invoices are created
2. All invoices created will be marked for [Auto Payment](https://github.com/dancameron/sprout-invoices-auto-billing/wiki/Documentation) (todo)
 1. If you wanted the invoices to be automatically charged within hours of the import than you will need your invoices to have a Due Date.
 2. If you want your admin to attempt the payment charge manually than they can use the AJAX button, e.g. http://s-v.me/c0zm
3. Admin will filter all invoices based on the due date, sending the ones to clients that don't have payment profiles (i.e. http://s-v.me/c0qu) and clicking the AJAX button to process the payment on those that do (i.e. http://s-v.me/c18k). 
 1. I can make all invoices imported to have the due date of the day it's imported.

This is my impression of how you wanted things to work.

**Comment by dancameron** [comment]
> Here's my rework of the mock-up. Please confirm my notes.
> ![](http://s-v.me/c0lP/Revised-7-20-15-Admin%20Workflow-%20Invoice%20Process.png)

*Client Identifier:* The identifier is the "Company" column within the CSV import. In your example CSV that you provided (#11) you would probably want to make the Company column a mix of "Customer_Name"  and "Customer_Account", e.g. "ADOBE EQUIPMENT (170)", otherwise you will run into conflicts.

If you end up needing to do this differently than I'll need to build a custom CSV importer.

**Comment by dancameron** [comment]
Something I forgot to mention is [Automatically Charge](https://github.com/dancameron/sprout-invoices-auto-billing/wiki/Documentation) option which I'm documenting now. If you don't want to use the cron method of capturing payments based on a due date than a payment will be automatically attempted whenever an invoice is created with this option. It just requires that this option be selected (which is something I can help automate if you want to go with this method instead).

**Comment by ddeitz** [comment]
Yes, I would like to go with this method.

**Comment by dancameron** [comment]
I'll close this than since all the work is already done.

**Comment by dancameron** [comment]
Oh wait...what method exactly will you be using? There are a lot of options here and I need to make sure you were going to use the "Automatically Charge" option and not the workflow outlined here - https://github.com/dancameron/sprout-invoices-auto-billing/issues/9#issuecomment-122982585

**Comment by ddeitz** [comment]
This is the method I want to move forward with:

Import CSV file and new invoices are created
All invoices created will be marked for Auto Payment (todo)
If you wanted the invoices to be automatically charged within hours of the import than you will need your invoices to have a Due Date.
If you want your admin to attempt the payment charge manually than they can use the AJAX button, e.g. http://s-v.me/c0zm
Admin will filter all invoices based on the due date, sending the ones to clients that don't have payment profiles (i.e. http://s-v.me/c0qu) and clicking the AJAX button to process the payment on those that do (i.e. http://s-v.me/c18k).
I can make all invoices imported to have the due date of the day it's imported.
This is my impression of how you wanted things to work.

See below for my notes:

****If you wanted the invoices to be automatically charged within hours of the import than you will need your invoices to have a Due Date.

*****I can make all invoices imported to have the due date of the day it's imported.

- Is it possible to do this, but include the ACTUAL due date on their invoices and in their payment dashboards. Could you maybe reference the "Invoice Date" field for the auto-payments? OR, if you could add a time to the cron, that would work too. (ex) cron would run on invoice date at 4PM.

*****All invoices created will be marked for Auto Payment (todo)

- I'm assuming this is just the default. That makes sense to me now.

**Comment by dancameron** [comment]
> Is it possible to do this, but include the ACTUAL due date on their invoices and in their payment dashboards. Could you maybe reference the "Invoice Date" field for the auto-payments? OR, if you could add a time to the cron, that would work too. (ex) cron would run on invoice date at 4PM.

What you're really asking for is a secondary date, one that would do the payment settlements. I rather not add this because there are so many ways that the invoice payment could be automatically done at the moment that things will get overly complicated (logically within the codebase and for you as a user). I would suggest that you find a method and stick to it, whether you use the invoice due date with my modification to set for auto pay OR *use the client option to Automatically Charge whenever an invoice is imported/created*.

I think the later would be easier, you could also set which clients you want to have their invoices automatically charged too.
